#!/bin/bash
# Session Start Hook - Initialize development environment
#
# This hook runs when:
# - Starting a new Claude Code session (you type `claude` in terminal)
# - Resuming a previous session with `/resume` command
# - After `/clear` command creates a fresh session
# - After compact operations (auto-compact or manual `/compact`)
#
# Context: The "startup" matcher fires when you first launch `claude` in your project.
# This is the perfect place to display environment status, set session variables,
# and provide helpful reminders about the project setup.

# Use CLAUDE_PROJECT_DIR if available, fallback to pwd
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"

# Check if Katana/Torii are running and report status
KATANA_RUNNING=$(lsof -ti:5050 > /dev/null 2>&1 && echo "true" || echo "false")
TORII_RUNNING=$(lsof -ti:8080 > /dev/null 2>&1 && echo "true" || echo "false")

echo "## Development Environment Status"
echo "- Katana (port 5050): $([ "$KATANA_RUNNING" = "true" ] && echo "running" || echo "stopped")"
echo "- Torii (port 8080): $([ "$TORII_RUNNING" = "true" ] && echo "running" || echo "stopped")"

# Check for world address from manifest (generated by sozo migrate)
MANIFEST_FILE="$PROJECT_DIR/contracts/manifest_dev.json"
if [ -f "$MANIFEST_FILE" ] && command -v jq &> /dev/null; then
  WORLD_ADDR=$(jq -r '.world.address' "$MANIFEST_FILE")
  if [ -n "$WORLD_ADDR" ] && [ "$WORLD_ADDR" != "null" ]; then
    echo "- World Address: $WORLD_ADDR"
  else
    echo "- World Address: not found in manifest"
  fi
else
  echo "- World Address: manifest not found (run sozo migrate)"
fi

# Environment variables for the session
if [ -n "$CLAUDE_ENV_FILE" ]; then
  cat >> "$CLAUDE_ENV_FILE" << EOF
export STARKNET_RPC="http://localhost:5050"
export DOJO_WORLD_ADDRESS="\$(jq -r '.world.address' "$MANIFEST_FILE" 2>/dev/null || echo 'not-deployed')"
EOF
fi

# Check .tool-versions and asdf status (in contracts directory)
if [[ -f "$PROJECT_DIR/contracts/.tool-versions" ]] && command -v asdf &> /dev/null; then
  echo ""
  echo "## Tool Versions (.tool-versions)"

  # Check if versions match what's installed
  OUTDATED=$(asdf current 2>&1 | grep -E "(not installed|No version)" || true)
  if [[ -n "$OUTDATED" ]]; then
    echo "- version mismatch detected:"
    echo "$OUTDATED" | head -5 | sed 's/^/    /'
    echo ""
    echo "  run: asdf install"
  else
    echo "- all tool versions match"
  fi
fi

echo ""
echo "available skills: dojo-tooling, dojo-analysis, dojo-dev, client-nextjs"

echo ""
echo "available mcp servers: next-devtools, cairo-coder, context7, sensei"

echo ""
echo "if an mcp server is disabled, ask the user to turn it on via the /mcp command"